In [4]:
import numpy as np

In [7]:
def predict_(x, theta):
	if not isinstance(x, np.ndarray) or not isinstance(theta, np.ndarray):
		return None
	if x.ndim != 2 or theta.ndim > 2:
		return None
	if theta.shape[0] != x.shape[1] + 1:
		return None
	
	m, n = x.shape
	X_Prime = np.hstack((np.ones((m, 1)), x))

	return X_Prime @ theta

In [12]:
def fit_(x, y, theta, alpha, max_iter):
	if not isinstance(x, np.ndarray) or not isinstance(y, np.ndarray) or not isinstance(theta, np.ndarray):
		return
	elif not isinstance(alpha, float) or not isinstance(max_iter, int):
		return
	elif x.size <= 0 or y.size <= 0 or theta.size <= 0 or alpha <= 0 or max_iter <= 0:
		return
	elif x.ndim != 2 or y.ndim != 2 or theta.ndim != 2:
		return
	m, n = x.shape
	if y.shape != (m, 1) or theta.shape != (n + 1, 1):
		return
	
	for _ in range(max_iter):
		y_hat = predict_(x, theta)

		error = y_hat - y

		X_Prime = np.hstack((np.ones((m, 1)), x))

		gradient = 1 / m * X_Prime.T @ error

		theta -= alpha * gradient
	return theta

In [13]:
x = np.array([[0.2, 2., 20.], [0.4, 4., 40.], [0.6, 6., 60.], [0.8, 8., 80.]])
y = np.array([[19.6], [-2.8], [-25.2], [-47.6]])
theta = np.array([[42.], [1.], [1.], [1.]])

# Example 0:
theta2 = fit_(x, y, theta, alpha = 0.0005, max_iter=42000)
print(repr(theta2))
# Output:
#array([[41.99..],[0.97..], [0.77..], [-1.20..]])

# Example 1:
print(predict_(x, theta2))
# Output:
#array([[19.5992..], [-2.8003..], [-25.1999..], [-47.5996..]])

array([[41.99888822],
       [ 0.97792316],
       [ 0.77923161],
       [-1.20768386]])
[[ 19.59925884]
 [ -2.80037055]
 [-25.19999994]
 [-47.59962933]]
