In [1]:
import numpy as np

In [3]:
def sigmoid_(x):
	if not isinstance(x, np.ndarray):
		return
	if x.size <= 0 or x.ndim != 2:
		return
	if x.shape[1] != 1:
		return
	
	return 1 / (1 + np.exp(-x))

In [12]:
# Example 1:
x = np.array([[-4]])
print(sigmoid_(x))
# Output:
#array([[0.01798620996209156]])

# Example 2:
x = np.array([[2]])
print(sigmoid_(x))
# Output:
#array([[0.8807970779778823]])

# Example 3:
x = np.array([[-4], [2], [0]])
print(sigmoid_(x))
# Output:
#array([[0.01798620996209156], [0.8807970779778823], [0.5]])

x = np.array([[100000000]])
print(sigmoid_(x))

x = np.array([[-10000]])
print(sigmoid_(x))

[[0.01798621]]
[[0.88079708]]
[[0.01798621]
 [0.88079708]
 [0.5       ]]
[[1.]]
[[0.]]


/tmp/ipykernel_69598/1444573904.py:9: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-x))
