In [1]:
import numpy as np

In [8]:
def data_spliter(x, y, proportion):
	if not isinstance(x, np.ndarray) or not isinstance(y, np.ndarray) or not isinstance(proportion, float):
		return
	if x.size <= 0 or y.size <= 0 or proportion <= 0.0 or proportion >= 1.0:
		return
	if x.ndim != 2 or y.ndim != 2:
		return
	if x.shape[0] != y.shape[0] or y.shape[1] != 1:
		return
	
	rng = np.random.default_rng(42)
	indices = np.arange(x.shape[0])
	rng.shuffle(indices)
	X_shuffled = x[indices]
	Y_shuffled = y[indices]

	trainingSet = int(x.shape[0] * proportion)

	X_trainset = X_shuffled[:trainingSet]
	Y_trainset = Y_shuffled[:trainingSet]
	X_testing = X_shuffled[trainingSet:]
	Y_testing = Y_shuffled[trainingSet:]

	print(repr((X_trainset, X_testing, Y_trainset, Y_testing)))

	return (X_trainset, X_testing, Y_trainset, Y_testing)

In [9]:
x1 = np.array([1, 42, 300, 10, 59]).reshape((-1, 1))
y = np.array([0, 1, 0, 1, 0]).reshape((-1, 1))
# Example 1:
data_spliter(x1, y, 0.8)
# Output:
#(array([ 1, 59, 42, 300]), array([10]), array([0, 0, 1, 0]), array([1]))
# Example 2:
data_spliter(x1, y, 0.5)
# Output:
#(array([59, 10]), array([ 1, 300, 42]), array([0, 1]), array([0, 0, 1]))

x2 = np.array([[ 1, 42], [300, 10], [ 59, 1], [300, 59], [ 10, 42]])
y = np.array([0, 1, 0, 1, 0]).reshape((-1, 1))
# Example 3:
data_spliter(x2, y, 0.8)
# Output:
#(array([[ 10, 42], [300, 59], [ 59, 1], [300, 10]]), array([[ 1, 42]]), array([0, 1, 0, 1]), array([0]))

# Example 4:
data_spliter(x2, y, 0.5)
# Output:
#(array([[59, 1], [10, 42]]), array([[300, 10], [300, 59], [ 1, 42]]), array([0, 0]), array([1, 1, 0]))

(array([[ 59],
       [300],
       [ 10],
       [ 42]]), array([[1]]), array([[0],
       [0],
       [1],
       [1]]), array([[0]]))
(array([[ 59],
       [300]]), array([[10],
       [42],
       [ 1]]), array([[0],
       [0]]), array([[1],
       [1],
       [0]]))
(array([[ 10,  42],
       [ 59,   1],
       [300,  59],
       [300,  10]]), array([[ 1, 42]]), array([[0],
       [0],
       [1],
       [1]]), array([[0]]))
(array([[10, 42],
       [59,  1]]), array([[300,  59],
       [300,  10],
       [  1,  42]]), array([[0],
       [0]]), array([[1],
       [1],
       [0]]))


(array([[10, 42],
        [59,  1]]),
 array([[300,  59],
        [300,  10],
        [  1,  42]]),
 array([[0],
        [0]]),
 array([[1],
        [1],
        [0]]))