In [5]:
import numpy as np

In [ ]:
class MyLogisticRegression():
	def __init__(self, theta, alpha=0.001, max_iter=1000):
		self.theta = theta
		self.alpha = alpha
		self.max_iter = max_iter

		if not isinstance(theta, np.ndarray) or not isinstance(alpha, float) or not isinstance(max_iter, int):
			return
		if alpha <= 0 or max_iter <= 0:
			return
		if theta.ndim != 2 or theta.shape[1] != 1:
			return


	def sigmoid_(self, x):
		if not isinstance(x, np.ndarray):
			return
		if x.size <= 0 or x.ndim != 2:
			return
		if x.shape[1] != 1:
			return

		return 1 / (1 + np.exp(-x))

	def predict_(self, x):
		if not isinstance(x, np.ndarray) or not isinstance(self.theta, np.ndarray):
			return
		if x.ndim != 2 or self.theta.ndim != 2:
			return
		if (self.theta.shape[0] != x.shape[1] + 1) or self.theta.shape[1] != 1:
			return

		m, n = x.shape

		X_prime = np.hstack((np.ones((m, 1)), x))

		y_hat = X_prime @ self.theta

		return self.sigmoid_(y_hat)

	def loss_(self, y, y_hat, eps=1e-15):
		if not isinstance(y, np.ndarray) or not isinstance(y_hat, np.ndarray):
			return
		if not isinstance(eps, float):
			return
		if y.ndim != 2 or y_hat.ndim != 2:
			return
		if y.shape[1] != 1 or y.shape != y_hat.shape:
			return

		y_hat_safe = np.clip(y_hat, eps, 1 - eps)
		
		m, n = y.shape

		loss_1 = y.T @ np.log(y_hat_safe)
		loss_0 = (1 - y).T @ np.log(1 - y_hat_safe)
		loss_sum = loss_1 + loss_0

		return -(1 / m) * loss_sum

	def fit_(self, x, y):
		if not isinstance(x, np.ndarray) or not isinstance(y, np.ndarray):
			return
		if x.ndim != 2 or y.ndim != 2:
			return
		if y.shape[1] != 1 or y.shape[0] != x.shape[0]:
			return

		for _ in range(self.max_iter):
			y_hat = self.predict_(x)

			error = y_hat - y

			m, n = x.shape
			X_prime = np.hstack((np.ones((m, 1)), x))

			gradient = (1 / m) * (X_prime.T @ error)

			self.theta -= self.alpha * gradient

In [22]:
X = np.array([[1., 1., 2., 3.], [5., 8., 13., 21.], [3., 5., 9., 14.]])
Y = np.array([[1], [0], [1]])
thetas = np.array([[2], [0.5], [7.1], [-4.3], [2.09]])
mylr = MyLogisticRegression(thetas)

# Example 0:
y_hat = mylr.predict_(X)
print(y_hat)
# Output:
#array([[0.99930437], [1.  ], [1.]])

# Example 1:
print(mylr.loss_(Y, y_hat))
# Output:
#11.513157421577002

# Example 2:
mylr.fit_(X, Y)
print(mylr.theta)
# Output:
#array([[ 2.11826435] [ 0.10154334] [ 6.43942899] [-5.10817488] [ 0.6212541 ]])

# Example 3:
y_hat = mylr.predict_(X)
print(y_hat)
# Output:
#array([[0.57606717] [0.68599807] [0.06562156]])

# Example 4:
print(mylr.loss_(Y, y_hat))
# Output:
#1.4779126923052268

[[0.99930437]
 [1.        ]
 [1.        ]]
[[11.51342395]]
[[ 2.11826435]
 [ 0.10154334]
 [ 6.43942899]
 [-5.10817488]
 [ 0.6212541 ]]
[[0.57606717]
 [0.68599807]
 [0.06562156]]
[[1.47791269]]
