In [10]:
import numpy as np

a = np.array([[0.56], [0.85], [0.33]])
b = np.array([[0.86], [0.45], [0.33]])
c = np.array([[0.96], [0.45], [0.23]])
d = np.array([[0.26], [0.05], [0.13]])

result = np.maximum(np.maximum(a, b), np.maximum(c, d))
print(result)

stacked = np.array([a.flatten(), b.flatten(), c.flatten(), d.flatten()])
print(stacked.shape)
print(stacked)

stacked2 = np.array([a[:, 0], b[:, 0], c[:, 0], d[:, 0]])
print(stacked2.shape)
print(stacked2)

result2 = np.max(stacked2, axis=0).reshape(-1, 1)
print(result2)

result3 = np.argmax(stacked2, axis=0)
print(result3)



[[0.96]
 [0.85]
 [0.33]]
(4, 3)
[[0.56 0.85 0.33]
 [0.86 0.45 0.33]
 [0.96 0.45 0.23]
 [0.26 0.05 0.13]]
(4, 3)
[[0.56 0.85 0.33]
 [0.86 0.45 0.33]
 [0.96 0.45 0.23]
 [0.26 0.05 0.13]]
[[0.96]
 [0.85]
 [0.33]]
[2 0 0]
