In [8]:
import numpy as np

In [25]:
class MyLinearRegression():
	def __init__(self, thetas, alpha=0.01, max_iter=100):
		if  not isinstance(thetas, np.ndarray) or not isinstance(alpha, float) or not isinstance(max_iter, int):
			return
		elif thetas.size <= 0 or alpha <= 0 or max_iter <= 0:
			return
		elif thetas.ndim != 2 or thetas.shape[1] != 1:
			return
		self.thetas = thetas
		self.alpha = alpha
		self.max_iter = max_iter
	
	def predict_(self, x):
		if not isinstance(x, np.ndarray) or not isinstance(self.thetas, np.ndarray):
			return
		elif x.size <= 0 or self.thetas.size <= 0:
			return
		elif x.ndim != 2 or self.thetas.ndim != 2:
			return

		m, n = x.shape

		X_Prime = np.hstack((np.ones((m, 1)), x))

		if self.thetas.shape != (n + 1, 1):
			return

		return X_Prime @ self.thetas
	
	def loss_(self, y, y_hat):
		m = y.shape[0]

		error = y_hat - y

		return 1 / (2 * m) * error.T @ error

	def fit_(self, x, y):
		if not isinstance(x, np.ndarray) or not isinstance(y, np.ndarray) or not isinstance(self.thetas, np.ndarray):
			return
		elif x.size <= 0 or y.size <= 0 or self.thetas.size <= 0:
			return
		elif x.ndim != 2 or y.ndim != 2 or self.thetas.ndim != 2:
			return
		m, n = x.shape
		if y.shape != (m, 1) or self.thetas.shape != (n + 1, 1):
			return

		self.thetas = self.thetas.astype(np.float64)
		
		for _ in range(self.max_iter):
			y_hat = self.predict_(x)

			error = y_hat - y

			X_Prime = np.hstack((np.ones((m, 1)), x))

			gradient = 1 / m * X_Prime.T @ error

			self.thetas -= self.alpha * gradient


In [26]:
x = np.array([[12.4956442], [21.5007972], [31.5527382], [48.9145838], [57.5088733]])
y = np.array([[37.4013816], [36.1473236], [45.7655287], [46.6793434], [59.5585554]])

lr1 = MyLinearRegression(np.array([[2], [0.7]]))

# Example 0.0:
y_hat = lr1.predict_(x)
print(repr(y_hat))
# Output:
""" array([[10.74695094],
[17.05055804],
[24.08691674],
[36.24020866],
[42.25621131]]) """

# Example 0.1:
#lr1.loss_elem_(y, y_hat)
# Output:
""" array([[710.45867381],
[364.68645485],
[469.96221651],
[108.97553412],
[299.37111101]]) """

# Example 0.2:
print(repr(lr1.loss_(y, y_hat)))
# Output:
#195.34539903032385

# Example 1.0:
lr2 = MyLinearRegression(np.array([[1], [1]]), 5e-8, 1500000)
lr2.fit_(x, y)
print(repr(lr2.thetas))
# Output:
""" array([[1.40709365],
[1.1150909 ]]) """

# Example 1.1:
y_hat = lr2.predict_(x)
print(repr(y_hat))
# Output:
""" array([[15.3408728 ],
[25.38243697],
[36.59126492],
[55.95130097],
[65.53471499]]) """

# Example 1.2:
#lr2.loss_elem_(y, y_hat)
# Output:
""" array([[486.66604863],
[115.88278416],
[ 84.16711596],
[ 85.96919719],
[ 35.71448348]]) """

# Example 1.3:
print(repr(lr2.loss_(y, y_hat)))
# Output:
#80.83996294128525

array([[10.74695094],
       [17.05055804],
       [24.08691674],
       [36.24020866],
       [42.25621131]])
array([[195.34539903]])
array([[1.40709365],
       [1.1150909 ]])
array([[15.3408728 ],
       [25.38243697],
       [36.59126492],
       [55.95130097],
       [65.53471499]])
array([[80.83996294]])
