In [1]:
import numpy as np

In [8]:
def gradient(x, y, theta):
	if not isinstance(x, np.ndarray) or not isinstance(y, np.ndarray) or not isinstance(theta, np.ndarray):
		return None
	if x.ndim != 2 or y.ndim != 2 or theta.ndim != 2:
		return None
	if x.shape[0] != y.shape[0] or x.shape[1] + 1 != theta.shape[0]:
		return None
	if y.shape[1] != 1 or theta.shape[1] != 1:
		return None
	

	m, n = x.shape
	X_Prime = np.concatenate((np.ones((m, 1)), x), axis=1)
	print(repr(X_Prime))

	X_Prime_2 = np.hstack((np.ones((m, 1)), x))
	print(repr(X_Prime_2))

	y_hat = X_Prime @ theta
	print(repr(y_hat))

	error = y_hat - y

	gradient = 1 / (y.shape[0]) * X_Prime.T @ error

	return gradient

In [9]:
x = np.array([
[ -6, -7, -9],
[ 13, -2, 14],
[ -7, 14, -1],
[ -8, -4, 6],
[ -5, -9, 6],
[ 1, -5, 11],
[ 9, -11, 8]])

y = np.array([2, 14, -13, 5, 12, 4, -19]).reshape((-1, 1))

theta1 = np.array([0, 3, 0.5, -6]).reshape((-1, 1))

# Example :
print(gradient(x, y, theta1))
# Output:
#array([[ -33.71428571], [ -37.35714286], [183.14285714], [-393.]])

# Example :
theta2 = np.array([0, 0, 0, 0]).reshape((-1, 1))
print(gradient(x, y, theta2))
# Output:
#array([[ -0.71428571], [ 0.85714286], [23.28571429], [-26.42857143]])

array([[  1.,  -6.,  -7.,  -9.],
       [  1.,  13.,  -2.,  14.],
       [  1.,  -7.,  14.,  -1.],
       [  1.,  -8.,  -4.,   6.],
       [  1.,  -5.,  -9.,   6.],
       [  1.,   1.,  -5.,  11.],
       [  1.,   9., -11.,   8.]])
array([[  1.,  -6.,  -7.,  -9.],
       [  1.,  13.,  -2.,  14.],
       [  1.,  -7.,  14.,  -1.],
       [  1.,  -8.,  -4.,   6.],
       [  1.,  -5.,  -9.,   6.],
       [  1.,   1.,  -5.,  11.],
       [  1.,   9., -11.,   8.]])
array([[ 32.5],
       [-46. ],
       [ -8. ],
       [-62. ],
       [-55.5],
       [-65.5],
       [-26.5]])
[[ -33.71428571]
 [ -37.35714286]
 [ 183.14285714]
 [-393.        ]]
array([[  1.,  -6.,  -7.,  -9.],
       [  1.,  13.,  -2.,  14.],
       [  1.,  -7.,  14.,  -1.],
       [  1.,  -8.,  -4.,   6.],
       [  1.,  -5.,  -9.,   6.],
       [  1.,   1.,  -5.,  11.],
       [  1.,   9., -11.,   8.]])
array([[  1.,  -6.,  -7.,  -9.],
       [  1.,  13.,  -2.,  14.],
       [  1.,  -7.,  14.,  -1.],
       [  1.,  -8.,  -4