In [1]:
import numpy as np

In [ ]:
def sigmoid_(x):
	if not isinstance(x, np.ndarray):
		return
	if x.size <= 0 or x.ndim != 2:
		return
	if x.shape[1] != 1:
		return
	
	return 1 / (1 + np.exp(-x))

In [23]:
def logistic_predict_(x, theta):
	if not isinstance(x, np.ndarray) or not isinstance(theta, np.ndarray):
		return
	if x.ndim != 2 or theta.ndim != 2:
		return
	if (theta.shape[0] != x.shape[1] + 1) or theta.shape[1] != 1:
		return
	
	m, n = x.shape

	X_prime = np.hstack((np.ones((m, 1)), x))

	y_hat = X_prime @ theta

	return sigmoid_(y_hat)

In [25]:
# Example 1
x = np.array([4]).reshape((-1, 1))
theta = np.array([[2], [0.5]])
print(repr(logistic_predict_(x, theta)))
# Output:
#array([[0.98201379]])

# Example 1
x2 = np.array([[4], [7.16], [3.2], [9.37], [0.56]])
theta2 = np.array([[2], [0.5]])
print(repr(logistic_predict_(x2, theta2)))
# Output:
#array([[0.98201379],
#[0.99624161],
#[0.97340301],
#[0.99875204],
#[0.90720705]])

# Example 3
x3 = np.array([[0, 2, 3, 4], [2, 4, 5, 5], [1, 3, 2, 7]])
theta3 = np.array([[-2.4], [-1.5], [0.3], [-1.4], [0.7]])
print(repr(logistic_predict_(x3, theta3)))
# Output:
#array([[0.03916572],
#[0.00045262],
#[0.2890505 ]])

array([[0.98201379]])
array([[0.98201379],
       [0.99624161],
       [0.97340301],
       [0.99875204],
       [0.90720705]])
array([[0.03916572],
       [0.00045262],
       [0.2890505 ]])
